str="hello how are you"
h=str.count('h')
e=str.count('e')
l=str.count('l')
w=str.count('w')
a=str.count('a') 
r=str.count('r')
e=str.count('e')
y=str.count('y')
o=str.count('o')
u=str.count('u')
puts "h = #{h}"
puts "e = #{e}"
puts "l = #{l}"
puts "w = #{w}"
puts "a = #{a}"
puts "r = #{r}"
puts "e = #{e}"
puts "y = #{y}"
puts "o = #{o}"
puts "u = #{u}"
